Modules Release 4.8.0 (2021-07-14)
DCC-SW: Added modules (2021-nov/XeonE5-2660v3)
DCC-SW: Removed standard modules: /apps/dcc/etc/ModulesSL73/modulefiles
DCC-SW: Using gnu/11.2.0 compiler
DCC-SW: Released modules (2021-nov/XeonE5-2660v3)
DCC-SW: Added modules (2020-aug/XeonE5-2660v3)
DCC-SW: Removed standard modules: /apps/dcc/etc/ModulesSL73/modulefiles
DCC-SW: Using gnu/9.3.0 compiler
DCC-SW: Released modules (2020-aug/XeonE5-2660v3)
Modules Release 4.8.0 (2021-07-14)
DCC-SW: Added modules (2021-nov/XeonE5-2660v3)
DCC-SW: Removed standard modules: /apps/dcc/etc/ModulesSL73/modulefiles
DCC-SW: Using gnu/11.2.0 compiler
DCC-SW: Released modules (2021-nov/XeonE5-2660v3)
DCC-SW: Added modules (2020-aug/XeonE5-2660v3)
DCC-SW: Removed standard modules: /apps/dcc/etc/ModulesSL73/modulefiles
DCC-SW: Using gnu/9.3.0 compiler
DCC-SW: Released modules (2020-aug/XeonE5-2660v3)
Modules Release 4.3.0 (2019-07-26)
DCC-SW: Added modules (2021-nov/XeonE5-2660v3)
DCC-SW: Removed standard modules: /apps/dcc/etc/ModulesSL73/modulefiles
DCC-SW: Using gnu/11.2.0 compiler
DCC-SW: Released modules (2021-nov/XeonE5-2660v3)
DCC-SW: Added modules (2020-aug/XeonE5-2660v3)
DCC-SW: Removed standard modules: /apps/dcc/etc/ModulesSL73/modulefiles
DCC-SW: Using gnu/9.3.0 compiler
Traceback (most recent call last):
  File "fepo4_1li.py", line 7, in <module>
    fepo4_1li = read('fepo4_1li.traj')
NameError: name 'read' is not defined
Traceback (most recent call last):
  File "fepo4_1li.py", line 7, in <module>
    fepo4_1li = read('fepo4_1li.traj')
NameError: name 'read' is not defined
Traceback (most recent call last):
  File "fepo4_1li.py", line 7, in <module>
    fepo4_1li = read('fepo4_1li.traj')
NameError: name 'read' is not defined
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
Traceback (most recent call last):
  File "fepo4_1li.py", line 7, in <module>
    fepo4_1li = read('fepo4_1li.traj')
NameError: name 'read' is not defined
Traceback (most recent call last):
  File "fepo4_1li.py", line 7, in <module>
    fepo4_1li = read('fepo4_1li.traj')
NameError: name 'read' is not defined
Traceback (most recent call last):
  File "fepo4_1li.py", line 7, in <module>
    fepo4_1li = read('fepo4_1li.traj')
NameError: name 'read' is not defined
Traceback (most recent call last):
  File "fepo4_1li.py", line 7, in <module>
    fepo4_1li = read('fepo4_1li.traj')
NameError: name 'read' is not defined
Traceback (most recent call last):
  File "fepo4_1li.py", line 7, in <module>
    fepo4_1li = read('fepo4_1li.traj')
NameError: name 'read' is not defined
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[26392,1],0]
  Exit code:    1
--------------------------------------------------------------------------
